name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug SSH Configuration
        run: |
          echo "=== DEBUG SSH CONFIGURATION ==="
          echo "SSH_HOST exists: ${{ secrets.SSH_HOST != '' }}"
          echo "SSH_USER exists: ${{ secrets.SSH_USER != '' }}"
          echo "SSH_PORT exists: ${{ secrets.SSH_PORT != '' }}"
          echo "SSH_PRIVATE_KEY exists: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
          echo "DEPLOY_PATH exists: ${{ secrets.DEPLOY_PATH != '' }}"
          
          # Verificar formato de la clave más detallado
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "=== PRIVATE KEY ANALYSIS ==="
            echo "Key length: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | wc -c)"
            echo "Key lines count: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | wc -l)"
            echo "First line: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | head -1)"
            echo "Last line: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | tail -1)"
            echo "Contains BEGIN: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | grep -c 'BEGIN' || echo 'NO')"
            echo "Contains END: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | grep -c 'END' || echo 'NO')"
            
            # Verificar tipo de clave
            if echo '${{ secrets.SSH_PRIVATE_KEY }}' | grep -q 'BEGIN OPENSSH PRIVATE KEY'; then
              echo "✅ Key type: OpenSSH format"
            elif echo '${{ secrets.SSH_PRIVATE_KEY }}' | grep -q 'BEGIN RSA PRIVATE KEY'; then
              echo "✅ Key type: RSA format"
            else
              echo "❌ Key type: Unknown or invalid format"
            fi
          else
            echo "❌ SSH_PRIVATE_KEY is empty!"
          fi
          
          echo "=== TESTING SSH CONNECTIVITY ==="
          echo "Host: ${{ secrets.SSH_HOST }}"
          echo "Port: ${{ secrets.SSH_PORT }}"
          echo "User: ${{ secrets.SSH_USER }}"
      
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          debug: true
          script: |
            echo "✅ SSH connection successful!"
            echo "Server info:"
            whoami
            hostname
            pwd
            ls -la ~ 